### ISSUE TITLE
serverParameter: cannot find symbol

### ISSUE THREAD

**Issue by serpent7776** [Kidoz-SDK/KIDOZ_ADMOB_ADAPTER#2]
I got errors while trying to compile:

src\com\kidoz\mediation\admob\adapters\KidozAdMobMediationBannerAdapter.java:54: error: cannot find symbol
`String appID = mKidozManager.getPublisherIdFromParams(serverParameter);`

symbol:   variable serverParameter
location: class KidozAdMobMediationBannerAdapter

src\com\kidoz\mediation\admob\adapters\KidozAdMobMediationBannerAdapter.java:55: error: cannot find symbol
`String token = mKidozManager.getPublisherTokenFromParams(serverParameter);`

symbol:   variable serverParameter
location: class KidozAdMobMediationBannerAdapter

**Comment by RinaKidoz** [comment]
Thanks for your message.

Please contact us at sdk@kidoz.net, so we can clarify few questions and assist you.

**Comment by RinaKidoz** [comment]
The issue was fixed. Thanks for your feedback.

**Comment by serpent7776** [comment]
That was fast, thanks :)
